#ifndef DEFINED_TIMER_H
#define DEFINED_TIMER_H

#define TIMER_BASE_FREQ 80000000

#define SERVO_INTR_TIMER_GROUP TIMER_GROUP_0
#define SERVO_INTR_TIMER_IDX TIMER_0
#define SERVO_INTR_TIMER_DIVIDER 3200
#define SERVO_INTR_TIMER_ALARM_VALUE 250 //100Hz, 10ms

#define BUTTON_INTR_TIMER_GROUP TIMER_GROUP_0
#define BUTTON_INTR_TIMER_IDX TIMER_1
#define BUTTON_INTR_TIMER_DIVIDER 6400
#define BUTTON_INTR_TIMER_ALARM_VALUE 250 //50Hz, 20ms
#endif
