#ifndef DEFINED_TIMER_H
#define DEFINED_TIMER_H

#define TIMER_BASE_FREQ 80000000

#define SERVO_INTR_TIMER_IDX 0
#define SERVO_INTR_TIMER_DIVIDER 6400
#define SERVO_INTR_TIMER_ALARM_VALUE 250 //50Hz, 20ms

#define BUTTON_INTR_TIMER_IDX 1
#define BUTTON_INTR_TIMER_DIVIDER 3200
#define BUTTON_INTR_TIMER_ALARM_VALUE 250 //100Hz, 10ms
void Defined_Timer_Init(void);

#endif
