#ifndef DEFINED_PWM_H
#define DEFINED_PWM_H
#include "driver/ledc.h"
//stepper
#define STEPPER_PWM_CHANNEL LEDC_CHANNEL_0
#define STEPPER_PWM_PIN GPIO_NUM_2
//servo
#define SERVO1_PWM_CHANNEL LEDC_CHANNEL_1
#define SERVO2_PWM_CHANNEL LEDC_CHANNEL_2
#define SERVO3_PWM_CHANNEL LEDC_CHANNEL_3
#define SERVO1_PWM_PIN GPIO_NUM_1
#define SERVO2_PWM_PIN GPIO_NUM_4
#define SERVO3_PWM_PIN GPIO_NUM_5

//motor
#define MOTOR1_PWM_CHANNEL LEDC_CHANNEL_4
#define MOTOR2_PWM_CHANNEL LEDC_CHANNEL_5
#define MOTOR3_PWM_CHANNEL LEDC_CHANNEL_6
#define MOTOR4_PWM_CHANNEL LEDC_CHANNEL_7
#define MOTOR1_PWM_PIN GPIO_NUM_6
#define MOTOR2_PWM_PIN GPIO_NUM_16
#define MOTOR3_PWM_PIN GPIO_NUM_9
#define MOTOR4_PWM_PIN GPIO_NUM_12
#endif
